"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import {
  ArrowLeft, Building2, ExternalLink, RefreshCw, Trash2,
  Loader2, FlaskConical, Share2, Copy, Check, Download,
  TrendingUp, Code2, Globe, AlertTriangle, Target, Zap, Brain,
} from "lucide-react";

import { BrandOverview } from "@/components/brand/BrandOverview";
import { SEOReport } from "@/components/brand/SEOReport";
import { TechReport } from "@/components/brand/TechReport";
import { IssuesList } from "@/components/brand/IssuesList";
import { SocialCards } from "@/components/brand/SocialCards";
import { CompetitorList } from "@/components/brand/CompetitorList";
import { PerformanceGauges } from "@/components/brand/PerformanceGauges";
import { AIGeoSection } from "@/components/brand/AIGeoSection";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Competitor {
  name: string;
  url?: string | null;
  description?: string | null;
  why_competitive?: string | null;
  evidence_source?: string | null;
}

interface CompetitorReport {
  id: string;
  competitor_url: string;
  competitor_name?: string | null;
  status: string;
  created_at: string;
}

interface BrandSummary {
  health_score_label?: string | null;
  tldr?: string | null;
  top_strengths?: { strength: string; detail?: string }[];
  critical_weaknesses?: { weakness: string; detail?: string }[];
  biggest_opportunities?: { opportunity: string; detail?: string }[];
  top_risks?: { risk: string; detail?: string }[];
  immediate_actions?: string[];
  data_gaps?: string[];
}

interface BrandReportProps {
  brand: {
    id: string;
    brand_url: string;
    brand_name?: string | null;
    brand_logo_url?: string | null;
    category?: string | null;
    completed_at?: string;
    analysis?: Record<string, Record<string, unknown> | null>;
    extracted_signals?: {
      seo_signals?: { sitemap_route_count?: number | null; [key: string]: unknown } | null;
      pagespeed?: unknown;
      tech_signals?: unknown;
    } | null;
    share_token?: string | null;
    competitors_discovered?: Competitor[];
    sections_generated?: string[];
  };
  linkedReports: CompetitorReport[];
  brandId: string;
  token: string;
  apiBase: string;
  onRefresh: () => void;
  onDelete: () => void;
  onNavigate: (reportId: string) => void;
  refreshing?: boolean;
  deleting?: boolean;
  refreshError?: string | null;
  readOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDate(iso?: string): string {
  if (!iso) return "—";
  try {
    return new Intl.DateTimeFormat("en-US", {
      month: "short", day: "numeric", year: "numeric",
    }).format(new Date(iso));
  } catch {
    return iso;
  }
}

function healthColor(label?: string | null): string {
  if (!label) return "text-[var(--text-3)]";
  const l = label.toLowerCase();
  if (l.includes("excellent") || l.includes("good")) return "text-emerald-400";
  if (l.includes("needs work")) return "text-amber-400";
  if (l.includes("critical")) return "text-red-400";
  return "text-[var(--accent-amber)]";
}

function buildCopySummary(brand: BrandReportProps["brand"], summary: BrandSummary | null | undefined): string {
  const lines: string[] = [
    `Brand Analysis: ${brand.brand_name || brand.brand_url}`,
    `Health: ${summary?.health_score_label ?? "—"}`,
    "",
    summary?.tldr ?? "",
  ];
  if (summary?.top_strengths?.length) {
    lines.push("", "Strengths:", ...summary.top_strengths.map((s) => `• ${s.strength}`));
  }
  if (summary?.critical_weaknesses?.length) {
    lines.push("", "Weaknesses:", ...summary.critical_weaknesses.map((w) => `• ${w.weakness}`));
  }
  if (summary?.immediate_actions?.length) {
    lines.push("", "Immediate Actions:", ...summary.immediate_actions.map((a, i) => `${i + 1}. ${a}`));
  }
  lines.push("", `Generated by SocietyOS — ${brand.brand_url}`);
  return lines.filter((l, i) => !(l === "" && (lines[i - 1] === "" || i === 0 || i === lines.length - 1))).join("\n");
}

// ---------------------------------------------------------------------------
// Tab config (shown below the overview)
// ---------------------------------------------------------------------------

const TAB_DEFS = [
  { id: "seo",         label: "SEO",         Icon: TrendingUp,    section: "seo_analysis" },
  { id: "performance", label: "Performance", Icon: Zap,           section: "__pagespeed__" },
  { id: "technical",   label: "Technical",   Icon: Code2,         section: "technical_analysis" },
  { id: "ai-geo",      label: "AI & Geo",    Icon: Brain,         section: "ai_geo_analysis" },
  { id: "issues",      label: "Issues",      Icon: AlertTriangle, section: "issue_checks" },
  { id: "social",      label: "Social",      Icon: Globe,         section: "social_media_discovery" },
  { id: "competitors", label: "Competitors", Icon: Target,        section: "__always__" },
];

// ---------------------------------------------------------------------------
// SWOT card
// ---------------------------------------------------------------------------

function SwotCard({
  title,
  items,
  renderItem,
  accentColor,
}: {
  title: string;
  items?: { [key: string]: string }[];
  renderItem: (item: { [key: string]: string }) => string;
  accentColor: string;
}) {
  const colorMap: Record<string, { text: string; bg: string; border: string }> = {
    emerald: { text: "text-emerald-400", bg: "rgba(52,211,153,0.07)", border: "rgba(52,211,153,0.2)" },
    red: { text: "text-red-400", bg: "rgba(248,113,113,0.07)", border: "rgba(248,113,113,0.2)" },
    cyan: { text: "text-[var(--accent-cyan)]", bg: "rgba(88,184,216,0.07)", border: "rgba(88,184,216,0.2)" },
    amber: { text: "text-amber-400", bg: "rgba(251,191,36,0.07)", border: "rgba(251,191,36,0.2)" },
  };
  const c = colorMap[accentColor] ?? colorMap.amber;

  return (
    <div
      className="rounded-xl p-4 border flex flex-col gap-2"
      style={{ background: c.bg, borderColor: c.border }}
    >
      <p className={`text-[10px] font-bold uppercase tracking-widest ${c.text}`}>{title}</p>
      {items && items.length > 0 ? (
        <ul className="flex flex-col gap-1.5">
          {items.map((item, i) => (
            <li key={i} className="text-xs text-[var(--text-2)] leading-relaxed">
              {renderItem(item)}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-xs text-[var(--text-3)] italic">None reported</p>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Tab bar
// ---------------------------------------------------------------------------

function TabBar({
  generated,
  hasPagesped,
  activeId,
  onSelect,
}: {
  generated: string[];
  hasPagesped: boolean;
  activeId: string;
  onSelect: (id: string) => void;
}) {
  const visible = TAB_DEFS.filter(({ section }) => {
    if (section === "__always__") return true;
    if (section === "__pagespeed__") return hasPagesped;
    if (section === "social_media_discovery")
      return generated.includes("social_media_discovery") || generated.includes("social_analysis");
    return generated.includes(section);
  });

  return (
    <div className="flex gap-1 flex-wrap border-b pb-0" style={{ borderColor: "var(--border-subtle)" }}>
      {visible.map(({ id, label, Icon }) => (
        <button
          key={id}
          onClick={() => onSelect(id)}
          className={`flex items-center gap-1.5 px-4 py-2 text-[11px] font-semibold whitespace-nowrap transition-colors border-b-2 -mb-px ${
            activeId === id
              ? "border-[var(--accent-amber)] text-[var(--accent-amber)]"
              : "border-transparent text-[var(--text-3)] hover:text-[var(--text-2)]"
          }`}
        >
          <Icon size={11} />
          {label}
        </button>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function BrandReport({
  brand,
  linkedReports,
  brandId,
  token,
  apiBase,
  onRefresh,
  onDelete,
  onNavigate,
  refreshing,
  deleting,
  refreshError,
  readOnly = false,
}: BrandReportProps) {
  const [copied, setCopied] = useState<"summary" | "link" | null>(null);
  const [sharing, setSharing] = useState(false);

  const analysis = brand.analysis ?? {};
  const generated = brand.sections_generated ?? [];
  const summary = analysis.brand_summary as BrandSummary | null | undefined;
  const pagespeed = brand.extracted_signals?.pagespeed as Parameters<typeof PerformanceGauges>[0]["pagespeed"] | null;
  const hasPagesped = !!(pagespeed && Object.values(pagespeed).some(Boolean));

  // Determine available tabs and default to first
  const availableTabs = TAB_DEFS.filter(({ section }) => {
    if (section === "__always__") return true;
    if (section === "__pagespeed__") return hasPagesped;
    if (section === "social_media_discovery")
      return generated.includes("social_media_discovery") || generated.includes("social_analysis");
    return generated.includes(section);
  });
  const [activeTab, setActiveTab] = useState(() => availableTabs[0]?.id ?? "seo");

  // If generated sections load after mount, reset to first available tab
  useEffect(() => {
    if (availableTabs.length && !availableTabs.find((t) => t.id === activeTab)) {
      setActiveTab(availableTabs[0].id);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [generated.join()]);

  const selectTab = useCallback((id: string) => {
    setActiveTab(id);
  }, []);

  async function handleCopySummary() {
    const text = buildCopySummary(brand, summary);
    await navigator.clipboard.writeText(text);
    setCopied("summary");
    setTimeout(() => setCopied(null), 2000);
  }

  async function handleShare() {
    setSharing(true);
    try {
      let shareToken = brand.share_token;
      if (!shareToken) {
        const res = await fetch(`${apiBase}/api/brands/${brandId}/share`, {
          method: "POST",
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.ok) {
          const data = await res.json();
          shareToken = data.share_token;
        }
      }
      if (shareToken) {
        const shareUrl = `${window.location.origin}/share/brand/${shareToken}`;
        await navigator.clipboard.writeText(shareUrl);
        setCopied("link");
        setTimeout(() => setCopied(null), 2500);
      }
    } catch {
      // silently fail
    } finally {
      setSharing(false);
    }
  }

  function handlePrint() {
    window.print();
  }

  return (
    <div className="max-w-5xl mx-auto px-6 py-10 print:px-0 print:py-4">
      {/* ---------------------------------------------------------------- */}
      {/* Header */}
      {/* ---------------------------------------------------------------- */}
      {!readOnly && (
      <div className="flex items-start justify-between gap-4 mb-6 print:hidden">
        <div className="flex items-center gap-3 min-w-0">
          <Link href="/my-brand" className="text-[var(--text-3)] hover:text-[var(--text-1)] transition-colors shrink-0">
            <ArrowLeft size={16} />
          </Link>
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              {brand.brand_logo_url ? (
                <img src={brand.brand_logo_url} alt="" width={20} height={20} className="rounded shrink-0 object-contain" />
              ) : (
                <Building2 size={16} className="text-[var(--accent-cyan)] shrink-0" />
              )}
              <h1 className="text-xl font-bold text-[var(--text-1)] truncate">
                {brand.brand_name || brand.brand_url}
              </h1>
              {brand.category && (
                <span className="text-[10px] px-1.5 py-0.5 rounded font-medium whitespace-nowrap border"
                  style={{ color: "var(--text-3)", borderColor: "var(--border-subtle)", background: "var(--bg-2)" }}>
                  {brand.category}
                </span>
              )}
            </div>
            <div className="flex items-center gap-3 mt-0.5">
              {brand.brand_url && (
                <a href={brand.brand_url} target="_blank" rel="noopener noreferrer"
                  className="text-xs text-[var(--text-3)] flex items-center gap-1 hover:text-[var(--accent-cyan)] transition-colors">
                  <ExternalLink size={10} />{brand.brand_url}
                </a>
              )}
              <span className="text-xs text-[var(--text-3)]">· {formatDate(brand.completed_at)}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {refreshError && <p className="text-xs text-red-400 max-w-xs text-right">{refreshError}</p>}

          <button onClick={handleCopySummary}
            className="btn-secondary flex items-center gap-1.5 text-xs"
            title="Copy executive summary">
            {copied === "summary" ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
            {copied === "summary" ? "Copied" : "Copy"}
          </button>

          <button onClick={handleShare} disabled={sharing}
            className="btn-secondary flex items-center gap-1.5 text-xs"
            title="Share report">
            {sharing ? <Loader2 size={12} className="animate-spin" /> : copied === "link" ? <Check size={12} className="text-emerald-400" /> : <Share2 size={12} />}
            {copied === "link" ? "Link copied" : "Share"}
          </button>

          <button onClick={handlePrint}
            className="btn-secondary flex items-center gap-1.5 text-xs"
            title="Export PDF via print">
            <Download size={12} />
            Export
          </button>

          <Link href="/my-brand/lab" className="btn-secondary flex items-center gap-1.5 text-xs" title="Pipeline Lab">
            <FlaskConical size={12} />
            Lab
          </Link>

          <button onClick={onRefresh} disabled={refreshing || deleting}
            className="btn-secondary flex items-center gap-1.5 text-xs">
            {refreshing ? <Loader2 size={12} className="animate-spin" /> : <RefreshCw size={12} />}
            Refresh
          </button>

          <button onClick={onDelete} disabled={deleting || refreshing}
            className="p-2 rounded-lg border text-[var(--text-3)] hover:text-red-400 hover:border-red-400/40 transition-colors"
            style={{ borderColor: "var(--border-subtle)", background: "var(--bg-1)" }}
            title="Delete brand">
            {deleting ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />}
          </button>
        </div>
      </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {/* Hero: health + tldr */}
      {/* ---------------------------------------------------------------- */}
      {summary && (
        <div className="rounded-xl border p-5 mb-5" style={{ background: "var(--bg-1)", borderColor: "var(--border-subtle)" }}>
          <div className="flex items-start gap-6">
            {summary.health_score_label && (
              <div className="shrink-0 text-center">
                <p className={`text-3xl font-black leading-none ${healthColor(summary.health_score_label)}`}>
                  {summary.health_score_label}
                </p>
                <p className="text-[10px] uppercase tracking-wider text-[var(--text-3)] mt-1 font-semibold">Brand Health</p>
              </div>
            )}
            {summary.tldr && (
              <p className="text-sm text-[var(--text-2)] leading-relaxed flex-1">{summary.tldr}</p>
            )}
          </div>
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {/* SWOT grid */}
      {/* ---------------------------------------------------------------- */}
      {summary && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
          <SwotCard
            title="Strengths"
            items={summary.top_strengths as { [key: string]: string }[]}
            renderItem={(i) => i.strength}
            accentColor="emerald"
          />
          <SwotCard
            title="Weaknesses"
            items={summary.critical_weaknesses as { [key: string]: string }[]}
            renderItem={(i) => i.weakness}
            accentColor="red"
          />
          <SwotCard
            title="Opportunities"
            items={summary.biggest_opportunities as { [key: string]: string }[]}
            renderItem={(i) => i.opportunity}
            accentColor="cyan"
          />
          <SwotCard
            title="Risks"
            items={summary.top_risks as { [key: string]: string }[]}
            renderItem={(i) => i.risk}
            accentColor="amber"
          />
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {/* Immediate actions */}
      {/* ---------------------------------------------------------------- */}
      {summary?.immediate_actions && summary.immediate_actions.length > 0 && (
        <div className="rounded-xl border p-5 mb-6" style={{ background: "var(--bg-1)", borderColor: "var(--border-subtle)" }}>
          <p className="text-xs font-semibold uppercase tracking-wider text-[var(--text-3)] mb-3">Immediate Actions (Next 30 Days)</p>
          <ol className="flex flex-col gap-2">
            {summary.immediate_actions.map((action, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-[var(--text-2)]">
                <span className="shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold text-[var(--accent-amber)]"
                  style={{ background: "rgba(242,169,59,0.12)" }}>
                  {i + 1}
                </span>
                {action}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {/* Brand Overview — always visible above tabs */}
      {/* ---------------------------------------------------------------- */}
      {analysis.brand_overview && (
        <div className="mb-6">
          <BrandOverview data={analysis.brand_overview as Parameters<typeof BrandOverview>[0]["data"]} />
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {/* Tab bar */}
      {/* ---------------------------------------------------------------- */}
      <TabBar
        generated={generated}
        hasPagesped={hasPagesped}
        activeId={activeTab}
        onSelect={selectTab}
      />

      {/* ---------------------------------------------------------------- */}
      {/* Tab panel */}
      {/* ---------------------------------------------------------------- */}
      <div className="mt-6">
        {activeTab === "seo" && analysis.seo_analysis && (
          <SEOReport
            data={analysis.seo_analysis as Parameters<typeof SEOReport>[0]["data"]}
            sitemapRouteCount={brand.extracted_signals?.seo_signals?.sitemap_route_count ?? null}
          />
        )}

        {activeTab === "performance" && hasPagesped && (
          <PerformanceGauges pagespeed={pagespeed} />
        )}

        {activeTab === "technical" && analysis.technical_analysis && (
          <TechReport
            data={analysis.technical_analysis as Parameters<typeof TechReport>[0]["data"]}
            extractedTech={brand.extracted_signals?.tech_signals as Parameters<typeof TechReport>[0]["extractedTech"]}
          />
        )}

        {activeTab === "ai-geo" && analysis.ai_geo_analysis && (
          <AIGeoSection data={analysis.ai_geo_analysis as Parameters<typeof AIGeoSection>[0]["data"]} />
        )}

        {activeTab === "issues" && analysis.issue_checks && (
          <IssuesList data={analysis.issue_checks as Parameters<typeof IssuesList>[0]["data"]} />
        )}

        {activeTab === "social" && (
          <SocialCards
            discoveryData={analysis.social_media_discovery as Parameters<typeof SocialCards>[0]["discoveryData"]}
            analysisData={analysis.social_analysis as Parameters<typeof SocialCards>[0]["analysisData"]}
          />
        )}

        {activeTab === "competitors" && (
          <CompetitorList
            competitors={brand.competitors_discovered ?? []}
            linkedReports={linkedReports}
            brandId={brandId}
            token={token}
            apiBase={apiBase}
            onNavigate={onNavigate}
          />
        )}
      </div>
    </div>
  );
}

